package bg.assignment.bg.backend.model.enums;

public enum ELoginResult
{
	//validation
	FAILED__IN__USERNAME_LESS_3CHAR,
	FAILED__IN__PASSWORD_LESS_3CHAR,
	FAILED__IN__MAIL_LESS_3CHAR,
	
	SUCCESS_IN__VALIDATED,

	//database
	FAILED__DB__USERNAME_NOT_EXISTS,
	FAILED__DB__AUTHENTICATION_DENIED,
	FAILED__DB__INTERNAL_ERROR,
	
	SUCCESS__DB__READY,
	
	SUCCESS__DB__AUTHENTICATED;
}
